config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, path: 'customers', controllers: { sessions: "customers/sessions", registrations: "customers/registrations" }
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions" }
  root to: "home#index"
  get '/signup_choice', to: 'home#signup'
  resources :buffets, only: [:new, :create, :edit, :update, :show, :index] do
    collection do
      get 'my_buffet'
      get 'search'
    end
    member do
      get 'active'
      get 'inactive'
      get 'rate'
      post 'rate', to: 'buffets#create_rate'
      get 'add_cover'
      post 'add_cover', to: 'buffets#create_add_cover'
      get 'index_ratings', to: 'buffets#index_ratings'
    end
  end
  resources :events, only: [:new, :create, :show, :edit, :update, :destroy] do
    member do
      post 'active'
      post 'inactive'
    end
    resources :prices, only: [:new, :create, :edit, :update]
    resources :albums, only: [:new, :create, :edit, :update]
    resources :orders, only: [:new, :create]
  end

  resources :orders, only: [:index, :show, :update] do
    resources :messages, only: [:index, :create, :edit, :update]
    collection do
      get 'user_index'
    end
    member do
      get 'confirm'
      get 'cancel'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :buffets, only: [:index, :show]
      resources :events, only: [:index] do
        member do
          get 'check_date'
        end
      end
    end
  end
end

app/models/buffet.rb
class Buffet < ApplicationRecord
  belongs_to :user, optional: true
  validates :name, :corporate_name, :register_number,
            :phone, :email, :address, :district, :state,
            :city, :payment_method, :description, presence: :true
  has_many :events
  has_one :order
  has_one :rate
  has_one_attached :image
end

app/controllers/api/v1/buffets_controller.rb
class Api::V1::BuffetsController < ActionController::API
  
  def index
    term = params[:query]
    buffets = []
    model_buffets= Buffet.where("name LIKE :term",term: "%#{term}%").order(:name).where(active: true)
    model_buffets.each do |b|
      buffets << {name: b.name, id: b.id}
    end
    render status: 200, json: buffets
  end

  def show
    begin
      b = Buffet.find(params[:id])
      raise ActiveRecord::RecordNotFound if b.nil?
      raise ActiveRecord::QueryAborted unless b.active
      
      buffet = {name: b.name, phone: b.phone, email: b.email, address: b.address,
        district: b.district, state: b.state, city: b.city,
        payment_method: b.payment_method,
        description: b.description, rating: get_rate(b)}
      render status: 200, json: buffet

    rescue ActiveRecord::RecordNotFound => e
      render status: 406, json: {error: "Buffet not found for this buffet_id"}
    rescue ActiveRecord::QueryAborted => e
      render status: 406, json: {error: "Buffet inactive"}
    end
  end

  private

  def get_rate(b)
    rates = Rate.where(buffet_id: b.id)
    acc = 0
    rates.each do |rate|
      acc = acc + rate.score
    end
    @rate_value = (acc.to_f/rates.length).round(1) unless rates.length == 0
  end
end

app/controllers/buffets_controller.rb
class BuffetsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index, :search, :rate, :create_rate, :index_ratings]
  before_action :set_buffet_for_current_user, only: [:my_buffet, :edit, :update, :active, :inactive, :add_cover, :create_add_cover]
  before_action :authenticate_customer!, only: [:rate, :create_rate]
  before_action :check_rate_condition, only: [:rate, :create_rate]

  def my_buffet
    @buffet = Buffet.find(current_user.buffet_id)
    @events = @buffet.events
    get_rate
  end

  def show
    @buffet = Buffet.find(params[:id])
    if current_user != nil and @buffet.id == current_user.buffet_id
      return redirect_to my_buffet_buffets_path
    end
    @events = @buffet.events.where(active: true)
    get_rate
  end

  def index
    @buffets = Buffet.all.where(active: true)
  end

  def new
    unless current_user.buffet_id == nil
      message = 'Já existe um Buffet cadastrado para esse usuário.'
      return redirect_to root_path, alert: message
    end
    @buffet = Buffet.new
  end

  def create
    unless current_user.buffet_id == nil
      message = 'Já existe um Buffet cadastrado para esse usuário.'
      redirect_to root_path, alert: message
    end
    @buffet = Buffet.new(get_params)
    if @buffet.save
      @user = current_user
      @user.update(buffet_id: @buffet.id)
      redirect_to root_path, notice: 'Buffet registrado com sucesso.'
    else
      flash.now[:alert] = 'Não foi possível registrar o Buffet.'
      render :new
    end
  end

  def edit; end

  def update
    if @buffet.update(get_params)
      message = 'Buffet atualizado com sucesso.'
      redirect_to my_buffet_buffets_path, notice: message
    else
      flash.now[:alert] = 'Não foi possível atualizar o Buffet.'
      render 'new'
    end
  end

  def search
    @term = params[:query]
    buffets_by_name_or_city = Buffet.where(
                                "name LIKE :term OR city LIKE :term",
                                term: "%#{@term}%"
                                ).order(:name).where(active: true)

    events_by_name = Event.where("events.name LIKE ?", "%#{@term}%")
                            .where(active: true)

    buffets_by_event_name = Buffet.joins(:events)
                            .where(events: { name: events_by_name
                            .pluck(:name) }).where(active: true).order(:name)
                            .distinct.order(:name)

    @buffets = (buffets_by_event_name | buffets_by_name_or_city)
    @buffets = (@buffets.sort_by { |buffet| buffet.name.downcase })
  end

  def active
    @buffet.active = true
    @buffet.save
    redirect_to @buffet
  end

  def inactive
    @buffet.active = false
    @buffet.save
    redirect_to @buffet
  end

  def rate
    @rate = Rate.new()
  end

  def create_rate
    p = params.require(:rate).permit(:score, :review, images:[])
    @rate = Rate.where(buffet_id: @buffet.id, customer_id: current_customer.id)
    if @rate.empty?
      @rate = Rate.new(p)
      @rate.buffet_id = @buffet.id
      @rate.customer_id = current_customer.id
      if @rate.save
        redirect_to @buffet, notice: 'Obrigado por avaliar!'
      else
        flash.now[:alert] = 'Erro ao avaliar.'
        render :rate
      end
    else
      @rate.update(p)
      redirect_to @buffet, notice: 'Obrigado por avaliar!'
    end
  end

  def add_cover; end

  def create_add_cover
    p = params.require(:buffet).permit(:image)
    @buffet.update(p)
    redirect_to @buffet
  end

  def index_ratings
    @buffet = Buffet.find(params[:id])
    @rates = Rate.where(buffet_id: @buffet.id)
  end

  private

  def get_params
    params.require(:buffet).permit(:name, :corporate_name, :register_number,
                                    :phone, :email, :address, :district,
                                    :state, :city, :payment_method,
                                    :description)
  end

  def set_buffet_for_current_user
    if current_user.buffet_id == nil
      message = 'Você precisa criar um Buffet para começar a utilizar a plataforma.'
      return redirect_to new_buffet_path, alert: message
    end
    @buffet = Buffet.find(current_user.buffet_id)
  end

  def check_rate_condition
    @order = Order.find_by(id: params[:order_id])
    message = "Você não pode avaliar esse Buffet."
    unless @order and @order.event_date < Date.today and @order.confirmed?
      return redirect_to root_path, alert: message
    end
    unless @order.customer_id == current_customer.id
      return redirect_to root_path, alert: message
    end
    @buffet = Buffet.find(params[:id])
  end

  def get_rate
    @recent_rates = Rate.where(buffet_id: @buffet.id).order(updated_at: :desc).limit(3)
    rates = Rate.where(buffet_id: @buffet.id)
    acc = 0
    rates.each do |rate|
      acc = acc + rate.score
    end
    @rate_value = (acc.to_f/rates.length).round(1) unless rates.length == 0
  end
end

app/views/buffets/_form.html.erb
<%= form_with(model: @buffet) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <% if @buffet.errors[:name].include?("não pode ficar em branco") %>
      <div class="buffet-advise">
        <%= t(:name) %> <%= @buffet.errors[:name].join(', ').strip %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :corporate_name %>
    <%= f.text_field :corporate_name %>
    <% if @buffet.errors[:corporate_name].include?("não pode ficar em branco") %>
      <div class="buffet-advise">
        <%= t(:corporate_name) %> <%= @buffet.errors[:corporate_name].join(', ').strip %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :register_number %>
    <%= f.text_field :register_number %>
    <% if @buffet.errors[:register_number].include?("não pode ficar em branco") %>
      <div class="buffet-advise">
        <%= t(:register_number) %> <%= @buffet.errors[:register_number].join(', ').strip %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
    <% if @buffet.errors[:phone].include?("não pode ficar em branco") %>
      <div class="buffet-advise">
        <%= t(:phone) %> <%= @buffet.errors[:phone].join(', ').strip %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
    <% if @buffet.errors[:email].include?("não pode ficar em branco") %>
      <div class="buffet-advise">
        <%= t(:email) %> <%= @buffet.errors[:email].join(', ').strip %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
    <% if @buffet.errors[:address].include?("não pode ficar em branco") %>
      <div class="buffet-advise">
        <%= t(:address) %> <%= @buffet.errors[:address].join(', ').strip %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :district %>
    <%= f.text_field :district %>
    <% if @buffet.errors[:district].include?("não pode ficar em branco") %>
      <div class="buffet-advise">
        <%= t(:district) %> <%= @buffet.errors[:district].join(', ').strip %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
    <% if @buffet.errors[:state].include?("não pode ficar em branco") %>
      <div class="buffet-advise">
        <%= t(:state) %> <%= @buffet.errors[:state].join(', ').strip %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
    <% if @buffet.errors[:city].include?("não pode ficar em branco") %>
      <div class="buffet-advise">
        <%= t(:city) %> <%= @buffet.errors[:city].join(', ').strip %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :payment_method %>
    <%= f.text_field :payment_method %>
    <% if @buffet.errors[:payment_method].include?("não pode ficar em branco") %>
      <div class="buffet-advise">
        <%= t(:payment_method) %> <%= @buffet.errors[:payment_method].join(', ').strip %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
    <% if @buffet.errors[:description].include?("não pode ficar em branco") %>
      <div class="buffet-advise">
        <%= t(:description) %> <%= @buffet.errors[:description].join(', ').strip %>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit 'Salvar Buffet' %>
  </div>
<% end %>

app/views/buffets/_inactive_message.html.erb
<h1>Este Buffet está inativo e portanto não está recebendo pedidos no momento.</h1>

<h2>Para mais informações você pode tentar contatar o dono do buffet no e-mail: <%= @buffet.email %></h2>

app/views/buffets/_index_buffets.html.erb
<div class="event-card-container">
  <% @buffets.each do |buffet| %>
    <div class="event-card">
      <h2>
        <% if buffet.image.present? %>
          <%= image_tag buffet.image, height: 120 %>
        <% end %>
        <%= link_to "#{buffet.name}", buffet_path(buffet), class: 'show-details-button' %>
      </h2>
      <p class="event-card-item"><%= buffet.city %> - <%= buffet.state %></p>
    </div>
  <% end %>
</div>

app/views/buffets/_index_events.html.erb
<h1>Eventos Disponíveis</h1>

<div class="event-card-container">
  <% @events.each do |event| %>
    <div class="event-card">
      <div>
        <h2 class="event-card-title">
          <%= event.name %>
          <% unless event.active %>
            ⛔ <p class="event-card-description">(Desativado)</p>
          <% end %>
        </h2>
        <div class="event-card-description"><%= event.description %></div>
        <div class="event-card-item"><strong>Capacidade Máxima:</strong> <%= event.max_qtd %></div>
        <% price = Price.find_by(event_id: event.id) %>
        <% if price %>
          <div class="event-card-item"><strong>A partir de:</strong> R$ <%= price.base_price %>,00</div>
          <!-- div class="event-card-item"><strong>Adicional por Pessoa:</strong> R$ <%= price.additional_person %>,00</div-->
          <!--div class="event-card-item"><strong>Adicional por Hora Extra:</strong> R$ <%= price.extra_hour %>,00</div-->
          <!--div class="event-card-item"><strong>Preço Base especial:</strong> R$ <%= price.sp_base_price %>,00</div-->
          <!--div class="event-card-item"><strong>Adicional por Pessoa especial:</strong> R$ <%= price.sp_additional_person %>,00</div-->
          <!--div class="event-card-item"><strong>Adicional por Hora Extra especial:</strong> R$ <%= price.sp_extra_hour %>,00</div-->
        <% else %>
          <div class="event-card-item">Valor ainda não informado</div>
        <% end %>
        <%= link_to 'Mostrar Detalhes', event_path(event.id), class: 'show-details-button' %>
      </div>
    </div>
  <% end %>
</div>

app/views/buffets/_index_ratings.html.erb
<div class="rate-container"><h1>Avaliações</h1></div>
<div class="rate-container">
  <% @recent_rates.each do |rate| %>
    <div class="rate-card">
      <h2><%= Customer.where(customer_id: rate.customer_id).name %></h2>
      <div class="rate-score">
        <%= rate.score %> 🌟
      </div>
      <div class="rate-review">
        <p><%= rate.review %></p>
      </div>
      <div class="rate-images">
        <% rate.images.each do |image| %>
          <%= image_tag image, height: 100 %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="rate-container">
  <%= link_to 'Mostrar todas', index_ratings_buffet_path(@buffet.id), class: "home-login-button owner" %>
</div>

app/views/buffets/add_cover.html.erb
<h1>Adicionar imagem de capa ao Buffet <%= @buffet.name %></h1>

<%= form_with(model: @buffet, url: add_cover_buffet_path(@buffet.id), method: :post) do |f| %>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit 'Salvar Buffet' %>
  </div>
<% end %>

app/views/buffets/edit.html.erb
<h1>Editar o Buffet <%= @buffet.name %></h1>

<%= render 'form' %>

app/views/buffets/index.html.erb
<h1>Lista de Buffets</h1>

<%= render 'index_buffets' %>

app/views/buffets/index_ratings.html.erb
<div class="rate-container"><h1>Avaliações</h1></div>
<div class="rate-container">
  <% @rates.each do |rate| %>
    <div class="rate-card">
      <h2><%= Customer.where(customer_id: rate.customer_id).name %></h2>
      <div class="rate-score">
        <%= rate.score %> 🌟
      </div>
      <div class="rate-review">
        <p><%= rate.review %></p>
      </div>
      <div class="rate-images">
        <% rate.images.each do |image| %>
          <%= image_tag image, height: 100 %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="rate-container">
  <%= link_to 'Voltar', buffet_path(@buffet.id), class: "home-login-button owner" %>
</div>

app/views/buffets/my_buffet.html.erb
<% if @buffet.active %>
  <%= render 'buffet_info' %>

  <div class="login-options" id="bottom-button">
    <%= link_to 'Editar Buffet', edit_buffet_path(current_user.buffet_id), class: "home-login-button owner" %>
    <%= link_to 'Adicionar Evento', new_event_path, class: "home-login-button owner" %>
    <%= link_to 'Desativar Buffet', inactive_buffet_path(@buffet.id), class: "home-login-button owner" %>
    <%= link_to 'Adicionar Capa', add_cover_buffet_path(@buffet.id), class: "home-login-button owner" %>
  </div>

  <%= render 'index_events' %>
  <%= render 'index_ratings' %>

<% else %>
  <%= render 'inactive_message' %>
  <%= link_to 'Ativar Buffet', active_buffet_path(@buffet.id), class: "home-login-button owner" %>
<% end %>

app/views/buffets/new.html.erb
<h1>Cadastrar um Buffet</h1>

<%= render 'form' %>

app/views/buffets/rate.html.erb
<h1>Avaliar o Buffet <%= @buffet.name %></h1>

<%= form_with(model: [@buffet, @rate], url: rate_buffet_path(@buffet.id, order_id: @order.id), method: :post) do |f| %>
  <div class="field">
    <%= f.label :score %>
    <%= f.range_field :score, min: 1, max: 5, step: 1, class: 'range-slider' %>
    <% if @rate.errors[:score].include?("não pode ficar em branco") %>
      <div class="buffet-advise">
        <%= t(:score) %> <%= @rate.errors[:score].join(', ').strip %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :review %>
    <%= f.text_field :review %>
    <% if @rate.errors[:review].include?("não pode ficar em branco") %>
      <div class="buffet-advise">
        <%= t(:description) %> <%= @rate.errors[:review].join(', ').strip %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :images %>
    <%= f.file_field :images, multiple: true %>
  </div>

  <div class="actions">
    <%= f.submit 'Salvar Avaliação' %>
  </div>
<% end %>

app/views/buffets/search.html.erb
<h1>Listando os buffets que tenham nome, cidade ou eventos cujo nome possui "<%= @term %>"</h1>

<%= render 'index_buffets' %>

app/views/buffets/show.html.erb
<% if @buffet.active %>
  <%= render 'buffet_info' %>
  <%= render 'index_events' %>
  <%= render 'index_ratings' %>

<% else %>
  <%= render 'inactive_message' %>
<% end %>