config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, path: 'customers', controllers: { sessions: "customers/sessions", registrations: "customers/registrations" }
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions" }
  root to: "home#index"
  get '/signup_choice', to: 'home#signup'
  resources :buffets, only: [:new, :create, :edit, :update, :show, :index] do
    collection do
      get 'my_buffet'
      get 'search'
    end
    member do
      get 'active'
      get 'inactive'
      get 'rate'
      post 'rate', to: 'buffets#create_rate'
      get 'add_cover'
      post 'add_cover', to: 'buffets#create_add_cover'
      get 'index_ratings', to: 'buffets#index_ratings'
    end
  end
  resources :events, only: [:new, :create, :show, :edit, :update, :destroy] do
    member do
      post 'active'
      post 'inactive'
    end
    resources :prices, only: [:new, :create, :edit, :update]
    resources :albums, only: [:new, :create, :edit, :update]
    resources :orders, only: [:new, :create]
  end

  resources :orders, only: [:index, :show, :update] do
    resources :messages, only: [:index, :create, :edit, :update]
    collection do
      get 'user_index'
    end
    member do
      get 'confirm'
      get 'cancel'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :buffets, only: [:index, :show]
      resources :events, only: [:index] do
        member do
          get 'check_date'
        end
      end
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :buffet, optional: true
  validates :buffet_id, :name, :description, :min_qtd,
            :max_qtd, :duration, :menu, presence: :true
  has_many :prices
  has_one :album
  has_one :price
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < ActionController::API
  require "holidays"
  def index
    begin
      term = params[:buffet_id]
      raise ActiveRecord::QueryAborted if term.nil?

      buffet = Buffet.find(term)
      raise ActiveRecord::RecordNotFound if buffet.nil?

      model_events = buffet.events.where(active: true)
      events = []
      model_events.each do |e|
        price = Price.find_by(event_id: e.id)
        events << {
          id: e.id, name: e.name, description: e.description, min_qtd: e.min_qtd,
          max_qtd: e.max_qtd, duration: e.duration, menu: e.menu, drinks: e.drinks,
          decoration: e.decoration, valet: e.valet, only_local: e.only_local, 
          prices: {base_price: price.base_price,
          additional_person: price.additional_person,
          extra_hour: price.extra_hour, sp_base_price: price.sp_base_price,
          sp_additional_person: price.sp_additional_person,
          sp_extra_hour: price.sp_extra_hour}
        }
      end

      render status: 200, json: events
    
    rescue ActiveRecord::QueryAborted => e
      render status: 412, json: {error: "Buffet_id required for this operation"}

    rescue ActiveRecord::RecordNotFound => e
      render status: 406, json: {error: "Buffet not found for this buffet_id"}

    end
  end

  def check_date
    return render status: 412, json: {
      error: "Date required for this operation"
      } if params[:date].nil?

    return render status: 412, json: {
      error: "Guest quantity required for this operation"
      } if params[:guest_qtd].nil?
    
    @event = Event.find_by(id: params[:id])
    return render status: 406, json: {
      error: "Event not found for this id"
      } if @event.nil?

    return render status: 406, json: {
      error: "Event is inactive"
      } unless @event.active

    @date = params[:date].to_date
    return render status: 412, json: {
      error: "Date must be future"
      } if @date < Date.today
    @guest_qtd = params[:guest_qtd].to_i
    return render status: 412, json: {
      error: "Guest quantity above max event's capacity"
      } if @guest_qtd > @event.max_qtd
    same_day_orders = Order.where(
                      buffet_id: @event.buffet_id, event_date: @date
                      ).where(order_status: :confirmed)
    if same_day_orders.any?
      response = {value: 0, availability: false}
      render status: 200, json: response
    else same_day_orders.empty?
      value = calculate_value
      response = {value: value, availability: true}
      render status: 200, json: response
    end
  end

  private

  def calculate_value
    price = Price.find_by(event_id: @event.id)
    aditional_people = 0
    has_plus_people = @event.min_qtd <= @guest_qtd
    aditional_people = @guest_qtd - @event.min_qtd if has_plus_people

    if not_business_day?
      base = price.sp_base_price
      aditional = price.sp_additional_person

      return value = base + (aditional_people * aditional)
    end

    base = price.base_price
    aditional = price.additional_person
    value = base + (aditional_people * aditional)
  end

  def not_business_day?
    day = @date
    !Holidays.on(day, :br).empty? || day.saturday? || day.sunday?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: :show

  def show
    @event = Event.find(params[:id])
    @buffet = Buffet.find(@event.buffet_id)
    @price = @event.price
    @album = @event.album
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(get_params)
    @event.buffet_id = current_user.buffet_id
    if @event.save
      message = 'Evento cadastrado com sucesso.'
      redirect_to my_buffet_buffets_path, notice: message
    else
      flash.now[:alert] = 'Não foi possível registrar o Evento.'
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])

    message = 'Você não tem permissão para editar esse evento.'
    return (
      redirect_to my_buffet_buffets_path, alert: message
      ) unless @event.buffet_id == current_user.buffet_id

    @buffet = Buffet.find(current_user.buffet_id)
  end

  def update
    @event = Event.find(params[:id])
    return redirect_to root_path unless @event.buffet_id == current_user.buffet_id
    if @event.update(get_params)
      message = 'Evento atualizado com sucesso.'
      redirect_to my_buffet_buffets_path, notice: message
    else
      @buffet = Buffet.find(current_user.buffet_id)
      flash.now[:alert] = 'Não foi possível atualizar o Evento.'
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    return redirect_to root_path unless @event.buffet_id == current_user.buffet_id
    ActiveRecord::Base.transaction do
      @event.prices.destroy_all
      @event.destroy
    end
    redirect_to my_buffet_buffets_path
  end

  def active
    @event = Event.find(params[:id])
    return redirect_to root_path unless @event.buffet_id == current_user.buffet_id
    @event.active = true
    @event.save
    redirect_to @event
  end

  def inactive
    @event = Event.find(params[:id])
    return redirect_to root_path unless @event.buffet_id == current_user.buffet_id
    @event.active = false
    @event.save
    redirect_to @event
  end

  private

  def get_params
    params.require(:event).permit(:name, :description, :min_qtd, :max_qtd,
                                  :duration, :menu, :drinks, :decoration,
                                  :valet, :only_local)
  end
end

app/views/events/_form.html.erb
<%= form_with(model: @event) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <% if @event.errors[:name].include?("não pode ficar em branco") %>
      <div class="buffet-advise">
        <%= t(:name) %> <%= @event.errors[:name].join(', ').strip %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
    <% if @event.errors[:description].include?("não pode ficar em branco") %>
      <div class="buffet-advise">
        <%= t(:description) %> <%= @event.errors[:description].join(', ').strip %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :min_qtd %>
    <%= f.number_field :min_qtd %>
    <% if @event.errors[:min_qtd].include?("não pode ficar em branco") %>
      <div class="buffet-advise">
        <%= t(:min_qtd) %> <%= @event.errors[:min_qtd].join(', ').strip %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :max_qtd %>
    <%= f.number_field :max_qtd %>
    <% if @event.errors[:max_qtd].include?("não pode ficar em branco") %>
      <div class="buffet-advise">
        <%= t(:max_qtd) %> <%= @event.errors[:max_qtd].join(', ').strip %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :duration %>
    <%= f.number_field :duration %>
    <% if @event.errors[:duration].include?("não pode ficar em branco") %>
      <div class="buffet-advise">
        <%= t(:duration) %> <%= @event.errors[:duration].join(', ').strip %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :menu %>
    <%= f.text_field :menu %>
    <% if @event.errors[:menu].include?("não pode ficar em branco") %>
      <div class="buffet-advise">
        <%= t(:menu) %> <%= @event.errors[:menu].join(', ').strip %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :drinks %>
    <%= f.check_box :drinks %>
    <% if @event.errors[:drinks].include?("não pode ficar em branco") %>
      <div class="buffet-advise">
        <%= t(:drinks) %> <%= @event.errors[:drinks].join(', ').strip %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :decoration %>
    <%= f.check_box :decoration %>
    <% if @event.errors[:decoration].include?("não pode ficar em branco") %>
      <div class="buffet-advise">
        <%= t(:decoration) %> <%= @event.errors[:decoration].join(', ').strip %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :valet %>
    <%= f.check_box :valet %>
    <% if @event.errors[:valet].include?("não pode ficar em branco") %>
      <div class="buffet-advise">
        <%= t(:valet) %> <%= @event.errors[:valet].join(', ').strip %>
      </div>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :only_local %>
    <%= f.check_box :only_local %>
    <% if @event.errors[:only_local].include?("não pode ficar em branco") %>
      <div class="buffet-advise">
        <%= t(:only_local) %> <%= @event.errors[:only_local].join(', ').strip %>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit 'Salvar Evento' %>
  </div>
<% end %>

app/views/events/_inactive_message.html.erb
<h1>Este evento está inativo e portanto não está recebendo pedidos no momento.</h1>

<h2>Para mais informações você pode tentar contatar o dono do buffet no e-mail: <%= @buffet.email %></h2>

app/views/events/_show.html.erb
<div class="buffet-card">
  <div class="h1-info">
    <h1>Exibindo o Evento <%= @event.name %> do Buffet <%= @buffet.name%> </h1>
  </div>

  <dl class="info-list">
    <dt>Nome:</dt>
    <dd><%= @event.name %></dd>

    <dt>Descrição:</dt>
    <dd><%= @event.description %></dd>

    <dt>Quantidade mínima de pessoas:</dt>
    <dd><%= @event.min_qtd %></dd>

    <dt>Quantidade máxima de pessoas:</dt>
    <dd><%= @event.max_qtd %></dd>
    
    <dt>Duração:</dt>
    <dd><%= @event.duration %></dd>

    <dt>Cardápio:</dt>
    <dd><%= @event.menu %></dd>

    <dt>Bebidas Alcoólicas:</dt>
    <% if @event.drinks %>
      <dd>Disponíveis</dd>
    <% else %>
      <dd>Não disponíveis</dd>
    <% end %>

    <dt>Decoração:</dt>
    <% if @event.decoration %>
      <dd>Disponível</dd>
    <% else %>
      <dd>Não disponível</dd>
    <% end %>

    <dt>Serviço de Estacionamento:</dt>
    <% if @event.valet %>
      <dd>Disponível</dd>
    <% else %>
      <dd>Não disponível</dd>
    <% end %>

    <dt>Exclusivo no local:</dt>
    <% if @event.only_local %>
      <dd>Evento somente disponível no local do buffet</dd>
    <% else %>
      <dd>Evento pode ser feito em qualquer outro local adequado</dd>
    <% end %>

    <% unless @price == nil%>
      <dt>Preço Base:</dt>
      <dd>R$ <%= @price.base_price %></dd>
      <dt>Adicional por Pessoa:</dt>
      <dd>R$ <%= @price.additional_person %></dd>
      <dt>Adicional por Hora Extra:</dt>
      <dd>R$ <%= @price.extra_hour %></dd>
      <dt>Preço Base Especial:</dt>
      <dd>R$ <%= @price.sp_base_price %></dd>
      <dt>Adicional por Pessoa Especial:</dt>
      <dd>R$ <%= @price.sp_additional_person %></dd>
      <dt>Adicional por Hora Extra Especial:</dt>
      <dd>R$ <%= @price.sp_extra_hour %></dd>
    <% end %>
  </dl>
</div>

<div class="login-options" id="bottom-button">
  <% if user_signed_in? and @event.buffet_id == current_user.buffet_id %>
    <%= button_to 'Editar Evento', edit_event_path(@event.id), method: :get, class: 'home-login-button owner' %>
    <%= button_to 'Excluir Evento', event_path(@event.id), method: :delete, class: 'home-login-button owner' %>
    <%= button_to 'Desativar Evento', inactive_event_path(@event.id), method: :post, class: 'home-login-button owner' %>
    <% if @price == nil %>
      <%= button_to 'Adicionar Preço', new_event_price_path(event_id: @event.id), method: :get, class: 'home-login-button owner' %>
    <% else %>
      <%= button_to 'Editar Preço', edit_event_price_path(event_id: @event.id, id: @price.id), method: :get, class: 'home-login-button owner' %>
    <% end %>
    <% if @album.present? and @album.images.attached? %>
      <%= button_to 'Editar Álbum', edit_event_album_path(event_id: @event.id, id: @album.id), method: :get, class: 'home-login-button owner' %>
    <% else %>
      <%= button_to 'Adicionar Imagens ao Álbum', new_event_album_path(event_id: @event.id), method: :get, class: 'home-login-button owner' %>
    <% end %>
  <% end %>

  <% if customer_signed_in? %>
    <%= button_to 'Realizar Pedido', new_event_order_path(@event), method: :get, class: 'home-login-button owner' %>
  <% end %>
</div>

<% if @album.present? and @album.images.attached? %>
  <div id="album-container">
    <% @album.images.each do |image| %>
      <%= image_tag image, height: 200 %>
    <% end %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editar o Evento <%= @event.name %> do Buffet <%= @buffet.name%> </h1>

<%= render 'form' %>

app/views/events/new.html.erb
<h1>Criar um novo evento</h1>

<%= render 'form' %>

app/views/events/show.html.erb
<% if @event.active %>
  <%= render 'show' %>
<% else %>
  <%= render 'inactive_message' %>
  <% if user_signed_in? and @event.buffet_id == current_user.buffet_id %>
    <%= button_to 'Ativar Evento', active_event_path(@event.id), method: :post, class: 'home-login-button owner' %>
  <% end %>
<% end %>