config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, path: 'customers', controllers: { sessions: "customers/sessions", registrations: "customers/registrations" }
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions" }
  root to: "home#index"
  get '/signup_choice', to: 'home#signup'
  resources :buffets, only: [:new, :create, :edit, :update, :show, :index] do
    collection do
      get 'my_buffet'
      get 'search'
    end
    member do
      get 'active'
      get 'inactive'
      get 'rate'
      post 'rate', to: 'buffets#create_rate'
      get 'add_cover'
      post 'add_cover', to: 'buffets#create_add_cover'
      get 'index_ratings', to: 'buffets#index_ratings'
    end
  end
  resources :events, only: [:new, :create, :show, :edit, :update, :destroy] do
    member do
      post 'active'
      post 'inactive'
    end
    resources :prices, only: [:new, :create, :edit, :update]
    resources :albums, only: [:new, :create, :edit, :update]
    resources :orders, only: [:new, :create]
  end

  resources :orders, only: [:index, :show, :update] do
    resources :messages, only: [:index, :create, :edit, :update]
    collection do
      get 'user_index'
    end
    member do
      get 'confirm'
      get 'cancel'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :buffets, only: [:index, :show]
      resources :events, only: [:index] do
        member do
          get 'check_date'
        end
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CadeBuffetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>

    <header>
      <nav>
        <h1>
          <%= link_to root_path do %>
            <div>
              <% banner_description = "Logo da Cadê buffet com as letras CB estilizadas em branco sobre um fundo lilás e o nome da marca na parte de baixo com o Cadê com letras roxas e o Buffet com letras brancas." %>
              <%= image_tag 'Full-Banner-minor.png', alt: banner_description, width: 150, height: 90 %>
            </div>
          <% end %>
        </h1>
        <div id="navigation-buttons" class="flex-container">
          <% if user_signed_in? %>
            <p><%= link_to 'Meu Buffet', my_buffet_buffets_path %></p>
            <p><%= link_to 'Pedidos', user_index_orders_path %></p>
          <% else %>
            <% if customer_signed_in? %>
              <p><%= link_to 'Meus Pedidos', orders_path %></p>
            <% end %>
            <p><%= link_to 'Lista de Buffets', buffets_path %></p>
            <p class="search-form">
              <%= form_with(url: search_buffets_path, method: :get, class: "search-form") do |f| %>
                <%= f.label :query, 'Buscar Buffet', class: "search-label" %>
                <%= f.text_field :query, class: "search-input" %>
                <%= f.submit 'Buscar', class: "search-button" %>
              <% end %>
            </p>
          <% end %>
        </div>
        <div id="login-area">
          <% if user_signed_in? %>
            <p>Conta: <%= current_user.email %></p>
            <p><%= button_to 'Sair', destroy_user_session_path, method: :delete %></p>
          <% elsif customer_signed_in? %>
            <p>Logado como: <%= current_customer.name %> <%= "<#{current_customer.email}>" %></p>
            <p><%= button_to 'Sair', destroy_user_session_path, method: :delete %></p>
          <% else %>
            <p><%= button_to 'Entrar', signup_choice_path, method: :get %></p>
          <% end %>
        </div>
      </nav>
    </header>

    <main>
      <div>
        <% if notice %>
          <p class="notice"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert"><%= alert %></p>
        <% end %>
      </div>
    <%= yield %>
    </main>

  </body>
</html>